USE [master]
GO

/****** Object:  Database [beer]    Script Date: 1/30/2017 11:05:17 PM ******/
CREATE DATABASE [beer]
GO

ALTER DATABASE [beer] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [beer].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [beer] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [beer] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [beer] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [beer] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [beer] SET ARITHABORT OFF 
GO

ALTER DATABASE [beer] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [beer] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [beer] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [beer] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [beer] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [beer] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [beer] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [beer] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [beer] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [beer] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [beer] SET ALLOW_SNAPSHOT_ISOLATION ON 
GO

ALTER DATABASE [beer] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [beer] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [beer] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [beer] SET  MULTI_USER 
GO

ALTER DATABASE [beer] SET DB_CHAINING OFF 
GO

ALTER DATABASE [beer] SET QUERY_STORE = ON
GO

ALTER DATABASE [beer] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 100, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO)
GO

ALTER DATABASE [beer] SET  READ_WRITE 
GO

