USE [master]
GO
/****** Object:  Database [beer]    Script Date: 2017-02-01 13:55:35 ******/
CREATE DATABASE [beer]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'beer', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\beer.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'beer_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\beer_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [beer] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [beer].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [beer] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [beer] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [beer] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [beer] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [beer] SET ARITHABORT OFF 
GO
ALTER DATABASE [beer] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [beer] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [beer] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [beer] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [beer] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [beer] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [beer] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [beer] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [beer] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [beer] SET  DISABLE_BROKER 
GO
ALTER DATABASE [beer] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [beer] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [beer] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [beer] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [beer] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [beer] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [beer] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [beer] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [beer] SET  MULTI_USER 
GO
ALTER DATABASE [beer] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [beer] SET DB_CHAINING OFF 
GO
ALTER DATABASE [beer] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [beer] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [beer] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [beer] SET QUERY_STORE = OFF
GO
USE [beer]
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [beer]
GO
/****** Object:  UserDefinedTableType [dbo].[Beer]    Script Date: 2017-02-01 13:55:35 ******/
CREATE TYPE [dbo].[Beer] AS TABLE(
	[Name] [varchar](50) NOT NULL,
	[Type] [varchar](50) NULL,
	[Price] [int] NULL,
	[Text] [text] NULL,
	[Brewery] [varchar](50) NULL,
	[AlcholPrecentage] [float] NULL,
	[Country] [varchar](50) NULL
)
GO
/****** Object:  Table [dbo].[Beer]    Script Date: 2017-02-01 13:55:35 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Beer](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[Type] [varchar](50) NULL,
	[Price] [int] NULL,
	[Text] [text] NULL,
	[Brewery] [varchar](50) NULL,
	[AlcholPrecentage] [decimal](5, 2) NULL,
	[Country] [varchar](50) NULL,
	[Added] [datetime] NULL,
	[Removed] [datetime] NULL,
	[SourceID] [int] NULL,
 CONSTRAINT [PK_Beer] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Sources]    Script Date: 2017-02-01 13:55:35 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Sources](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[name] [varchar](max) NOT NULL,
	[Adress] [varchar](max) NULL,
 CONSTRAINT [PK_Sources] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
ALTER TABLE [dbo].[Sources]  WITH CHECK ADD  CONSTRAINT [FK_Sources_Sources] FOREIGN KEY([ID])
REFERENCES [dbo].[Sources] ([ID])
GO
ALTER TABLE [dbo].[Sources] CHECK CONSTRAINT [FK_Sources_Sources]
GO
/****** Object:  StoredProcedure [dbo].[UpdateSource]    Script Date: 2017-02-01 13:55:35 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[UpdateSource]
	-- Add the parameters for the stored procedure here
	@sourceName[varchar](50) = '',
	@Adress[varchar](50) = '',
	@beerList Beer READONLY
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
DECLARE @CpmID AS int
	SET @CpmID = (SELECT TOP(1) ID FROM Sources WHERE Name = @sourceName)

	IF @CpmID IS NULL
	BEGIN
		BEGIN
		INSERT INTO dbo.Sources (name,Adress)
		VALUES (@sourceName,@Adress)
		END
		set @CpmID = SCOPE_IDENTITY()  
	END
END

Begin
UPDATE Beer
set Removed = GETDATE()
where beer.Name not in (select Name from @beerList) and beer.ID = @CpmID and Removed is NULL
END

Begin
insert into Beer (Name,Type,Price,Text,Brewery,AlcholPrecentage,Country,Added,SourceID)
Select t1.Name,t1.Type,t1.Price,t1.Text,t1.Brewery,t1.AlcholPrecentage,t1.Country,GETDATE(),@CpmID from @beerList as t1
where t1.Name not in (select t2.name from beer as t2 where t2.Removed is NULL and t2.SourceID =@CpmID)
END

GO
USE [master]
GO
ALTER DATABASE [beer] SET  READ_WRITE 
GO
